services:
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - puid=1000
      - pgid=1000
      - tz=america/chicago
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    network_mode: host
    restart: unless-stopped
